#!/usr/bin/env python3
"""
Download Yoruba Bible (eBible.org – yor translation) and write bible_data.js.
Keys match audio_map.js: "bookNum-chapterNum" (1-indexed).

Run:  python3 fetch_bible_data.py
Output: bible_data.js  (~5 MB)
"""
import os, json, re, zipfile, io, urllib.request

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

URL = 'https://ebible.org/Scriptures/yor_usfm.zip'

BOOK_ORDER = [
    'GEN','EXO','LEV','NUM','DEU','JOS','JDG','RUT',
    '1SA','2SA','1KI','2KI','1CH','2CH','EZR','NEH',
    'EST','JOB','PSA','PRO','ECC','SNG','ISA','JER',
    'LAM','EZK','DAN','HOS','JOL','AMO','OBA','JON',
    'MIC','NAM','HAB','ZEP','HAG','ZEC','MAL',
    'MAT','MRK','LUK','JHN','ACT','ROM','1CO','2CO',
    'GAL','EPH','PHP','COL','1TH','2TH','1TI','2TI',
    'TIT','PHM','HEB','JAS','1PE','2PE','1JN','2JN',
    '3JN','JUD','REV',
]

def usfm_to_verses(text):
    """Extract verses from USFM text; return dict {chNum: [v1, v2, ...]}."""
    chapters = {}
    ch = 0
    for line in text.splitlines():
        line = line.strip()
        m = re.match(r'\\c\s+(\d+)', line)
        if m:
            ch = int(m.group(1))
            chapters[ch] = []
            continue
        m = re.match(r'\\v\s+(\d+)\s+(.*)', line)
        if m and ch:
            verse_text = re.sub(r'\\[a-z]+\*?', '', m.group(2)).strip()
            verse_text = re.sub(r'\s+', ' ', verse_text)
            chapters[ch].append(verse_text)
    return chapters

print(f'Downloading {URL} …')
with urllib.request.urlopen(URL, timeout=60) as resp:
    data = resp.read()
print(f'Downloaded {len(data)//1024} KB')

bible_data = {}

with zipfile.ZipFile(io.BytesIO(data)) as zf:
    names = zf.namelist()
    for book_idx, book_code in enumerate(BOOK_ORDER, 1):
        # find matching file in zip (case-insensitive)
        match = next(
            (n for n in names
             if re.search(rf'[-/]{book_code}\.usfm$', n, re.I)
             or re.search(rf'[-/]\d{{2,3}}{book_code}\.usfm$', n, re.I)
             or n.lower().endswith(f'{book_code.lower()}.usfm')),
            None
        )
        if match is None:
            # Try USFM numbering like 01GEN.usfm
            match = next(
                (n for n in names if book_code.lower() in n.lower() and n.endswith('.usfm')),
                None
            )
        if match is None:
            print(f'  WARNING: no USFM for {book_code}')
            continue
        text = zf.read(match).decode('utf-8', errors='replace')
        chapters = usfm_to_verses(text)
        for ch_num, verses in chapters.items():
            if verses:
                bible_data[f'{book_idx}-{ch_num}'] = verses
        print(f'  {book_code}: {len(chapters)} chapters')

lines = [
    '// Auto-generated by fetch_bible_data.py — Yoruba Bible (eBible.org yor)',
    f'// Books: {len(set(k.split("-")[0] for k in bible_data))}  |  '
    f'Chapters: {len(bible_data)}  |  '
    f'Verses: {sum(len(v) for v in bible_data.values())}',
    'window.BIBLE_DATA = ',
    json.dumps(bible_data, ensure_ascii=False, indent=2),
    ';',
]

out = os.path.join(BASE_DIR, 'bible_data.js')
with open(out, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print(f'\n✓  bible_data.js — {len(bible_data)} chapter entries')
