#!/usr/bin/env python3
"""
Generate audio_map.js from local audio files.
Run:  python3 generate_audio_map.py
Output: audio_map.js  (keys: "bookNum-chapterNum", e.g. "1-1")
"""
import os, json, re

BASE_DIR  = os.path.dirname(os.path.abspath(__file__))
AUDIO_DIR = os.path.join(BASE_DIR, 'Bíbélì kíkà(1)')

audio_map = {}

for folder in sorted(os.listdir(AUDIO_DIR)):
    fpath = os.path.join(AUDIO_DIR, folder)
    if not os.path.isdir(fpath):
        continue
    m = re.match(r'^\((\d+)\)', folder)
    if not m:
        continue
    book_num = int(m.group(1))

    files = sorted(
        f for f in os.listdir(fpath)
        if os.path.isfile(os.path.join(fpath, f))
        and f.lower().endswith(('.mp3', '.wav'))
    )

    for ch_idx, fname in enumerate(files, 1):
        key = f'{book_num}-{ch_idx}'
        audio_map[key] = f'Bíbélì kíkà(1)/{folder}/{fname}'

lines = ['// Auto-generated by generate_audio_map.py — do not edit by hand.',
         'window.AUDIO_MAP = {']
for k, v in audio_map.items():
    lines.append(f'  {json.dumps(k)}: {json.dumps(v)},')
lines.append('};\n')

out = os.path.join(BASE_DIR, 'audio_map.js')
with open(out, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'✓  audio_map.js — {len(audio_map)} entries')
for b in sorted({int(k.split("-")[0]) for k in audio_map}):
    n = sum(1 for k in audio_map if k.startswith(f'{b}-'))
    print(f'   Book {b:2d}: {n} chapters')
